version: "3.8"

services:

  frontend:

    build:
      context: ./frontend

    image: frontend

    ports:
      - "80:80"

    depends_on:
      - backend

  backend:

    build:
      context: ./app

    image: backend

    ports:
      - "8000:8000"



